projectt/projects/urls.py
from django.urls import path
from .views import *
app_name = "projects"
urlpatterns = [
    path('', index),
    path("index", index, name="index"),
    path("categorie/<int:cid>", view, name="show"),
    path("search", search, name="search"),
    path("details/<int:pid>", details, name="detail"),
    path('mydonations/',my_donations,name='mydonations'),
    
    path('projects/',ProjectsList.as_view(),name="projects"),
    path('addproject/',add_project,name="add-project"),
    path('project/<int:pk>',ProjectDetail.as_view(),name="project"),
    path('addcomment/<project_id>',add_comment,name="addcomment"),
    # path('donate/<project_id>',add_donations,name="add-donation"),
    path('updateproject/<int:project_id>',editproject,name="editproject"),
    path('deleteproject/<int:project_id>',deleteproject,name="deleteproject"),
    path('myprojects/',my_projects,name='myprojects'),
    path("report/<int:pid>", reportproject, name="reportproject"),    # hadeer
    path("comment/<int:pid>", reportcomment, name="reportcomment"),    # hadeer
    path("donate/<int:pid>", donate, name="donate"),    # hadeer
    path("rate/<int:pid>", rate, name="rate"),    # hadeer
    
]

projectt/projectt/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import *
from django.conf.urls.static import static
from django.conf import settings
from crowdFunding.views import login, home, edit, delete,signup, activate, mylogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login',login,name='login'),
    path('home', home, name='home'),
    path('edit',edit, name='user_edit'),
    path('delete', delete, name='user_del'),
    path('', include('projects.urls')),
    path('signup/',signup , name = 'signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
    path('logout',mylogout, name='logout')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectt/projects/forms.py
from tracemalloc import start
from django.forms import ModelForm, ValidationError
from django import forms
from .models import *
from django.core.validators import RegexValidator
from django.forms.widgets import CheckboxSelectMultiple
from .models import Project,Categories,ProjectTage
import datetime
from django.template.defaultfilters import slugify
class SearchForm(forms.Form):
    mode = forms.ChoiceField(required=True,choices=(('1',"Tage"),('2',"title")))
    search = forms.CharField(required=True)
class ReportForm(forms.Form):
    content = forms.CharField(required=True)
#=======================================
class ReportFormProject(forms.Form):
    content = forms.CharField(required=True)
    # hadeer
class ReportFormComment(forms.Form):
    content = forms.CharField(required=True)
    # hadeer
class DonationForm(forms.Form):
    amount = forms.IntegerField(required=True)
    # hadeer
class RatingForm(forms.Form):
    rate = forms.IntegerField(required=True)
    # hadeer
    #================================================

class ProjectForm (forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm,self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Categories.objects.all()
        self.fields['category'].widget.attrs.update({'class':'form-control'})
        self.fields["tags"].widget = CheckboxSelectMultiple()
        self.fields["tags"].queryset = ProjectTage.objects.all()

    class Meta:
        model = Project
        
        fields=('title','details','category','totalTarget','start_date','end_date','tags','image')
        #abels={'title':' ','details':'','category':'Category','target':'','start_date':'','end_date':''}
       
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'details':forms.TextInput(attrs={'class':'form-control'}),
            'totalTarget':forms.NumberInput(attrs={'class':'form-control'}),
            'start_date':forms.DateTimeInput(attrs={'class':'form-control'}),
            'end_date':forms.DateTimeInput(attrs={'class':'form-control'}),
            }
        tags = forms.ModelMultipleChoiceField(
        queryset=ProjectTage.objects.all(),
        widget=forms.CheckboxSelectMultiple
        )
        
 
    def clean(self): 
           cleaned_date=super().clean()
           data =cleaned_date.get('start_date')
           data2= cleaned_date.get('end_date')
           if datetime.datetime.now().date() > data :
                #    print (datetime.datetime.now())
                   print(data)
                   raise ValidationError("start date cannot be a past date")
           elif datetime.datetime.now().date() > data2 :
                 raise ValidationError("end date cannot be a past date")  
           elif  data2 == data :
                raise ValidationError("end date cannot be = start date")  
           
           elif data2 < data :
               raise ValidationError("end date cannot before start date")
           else :
                pass
                 
               
                   
                   
           
               
     
        #Validation #DataFlair

    

projectt/projects/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.urls import reverse_lazy
#from django.db.models import Avg
from django.shortcuts import get_object_or_404,redirect,render,HttpResponseRedirect
from django.contrib import messages
from django.views.generic import ListView,DetailView,CreateView

# Create your views here.


# home views
#from projectt.crowdFunding import models
from crowdFunding.models import myuser


def index(request):
    projects = Project.objects.all()
    ProjectRate = Project.objects.annotate(avg=Avg("rate__rate")).order_by('avg')[:5]
    lastProject = Project.objects.order_by('id')[:5]
    featureProjects = FeatureProjects.objects.all()
    categories = Categories.objects.all()
    context = {
        "projects": projects,
        "ProjectRate": ProjectRate,
        "lastProject": lastProject,
        "featureProjects": featureProjects,
        "categories": categories
    }
    return render(request, "projects/projectHome.html", context)


def view(request, cid):
    projects = get_object_or_404(Categories, id=cid)
    categories = Categories.objects.all()
    context = {
        "projects": projects.project,
        "categories": categories,
        "categoryName": projects.name
    }

    return render(request, "projects/view.html", context)


def search(request):
    form = SearchForm(request.GET)
    if form.is_valid():
        mode = form.cleaned_data.get("mode")
        searching = form.cleaned_data.get("search")
        if mode == "1":
            projects = ProjectTage.objects.filter(tage=searching)
            if projects:
                projects = projects[0].project_all()
        else:
            projects = Project.objects.filter(title=searching)
    categories = Categories.objects.all()
    context = {
        "projects": projects,
        "categories": categories,
        "categieName": searching
    }
    return render(request, "projects/view.html", context)


def details(request, pid):
    categories = Categories.objects.all()
    authenticated=None
    owned=None
    project = get_object_or_404(Project, id=pid)
    if 'Email' in request.session :
             if myuser.objects.get(Email=request.session['Email'])==project.user:
                 print("yes tnis is owner ", myuser.objects.get(Email=request.session['Email']))
                 owned=True
             else :
                 authenticated=myuser.objects.get(Email=request.session['Email'])
             
             
            
    else:
            authenticated=None
            owned=None

    context = {
        "categories": categories,
        "images": project.allImage(),
        "project": project,
        "relativesProject": project.relativeProject(),
        "commentcount": project.comments().count(),
        "owned":owned,
        "authenticated":authenticated
    }
    return render(request, "projects/details.html", context)



############################################################
class ProjectsList(ListView):
    template_name="projects/AllProjects.html"
    model=Project
    def get_query(self):
        return Project.objects.all()
   
    def get_context_data(self,**kwargs):
        if 'Email' in self.request.session :
             authenticated=myuser.objects.get(Email=self.request.session['Email'])
        else:
            authenticated=None
        context = super().get_context_data(**kwargs)
        context['authenticated'] = authenticated
        return context
       

class ProjectDetail(DetailView):
    model=Project
    template_name="projects/project.html"
    def get_context_data(self,**kwargs):
        if 'Email' in self.request.session :
             authenticated=myuser.objects.get(Email=self.request.session['Email'])
             owned=None
             if myuser.objects.get(Email=self.request.session['Email'])==self.object.user:
                 print("yes tnis is owner ", myuser.objects.get(Email=self.request.session['Email']))
                 owned=True
             else :
                 print("diffrent one ", myuser.objects.get(Email=self.request.session['Email']))
        else:
            authenticated=None
        context = super().get_context_data(**kwargs)
        context['authenticated'] = authenticated
        context['owned'] = owned
        return context
    
def deleteproject (req,project_id):
        obj=Project.objects.get(pk=project_id)
        obj.delete()
        return HttpResponseRedirect("/myprojects")
    
    
def add_comment (req,project_id):
     if req.method=="POST" :
         print(Project.objects.get(pk=project_id))
         comment=Comment.objects.create(user=myuser.objects.get(Email=req.session['Email']),
                                        project=Project.objects.get(pk=project_id), content=req.POST['content'])
     return HttpResponseRedirect(f"/details/{project_id}")
         
# def add_donations (req,project_id):
#      if req.method=="POST" :
#          print(Project.objects.get(pk=project_id))
#          donation=Donation.objects.create(owner=myuser.objects.get(Email=req.session['Email']),
#            project=Project.objects.get(pk=project_id),amount=req.POST['rate'])
#      return HttpResponseRedirect(f"/details/{project_id}")

def my_projects(req):
    list=Project.objects.filter(user=myuser.objects.get(Email=req.session['Email']))
    return render (req,'projects/profile.html',{'list':list})

class newForm(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/NewProject.html'
    success_url = reverse_lazy('projects')
    
    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
        
    def form_valid(self, form): 
        obj = form.save(commit=False)
        obj.user = myuser.objects.get(Email=self.request.session['Email'])
        obj.save()        
        return HttpResponseRedirect(self.success_url)
    
    
    
def add_project(request):
    submitted=False
    if request.method=="GET" :
        # new form
        form=ProjectForm()
        if 'submitted' in request.GET :
            # from the 2nd second request
            submitted=True
        return render (request,'projects/NewProject.html',{'form':form,'submitted':submitted})
    else :
        #req is post data already in
        form=ProjectForm(request.POST,request.FILES)
        
        if form.is_valid():
            project=form.save(commit=False)
            project.user=myuser.objects.get(Email=request.session['Email'])
            if project.start_date >= project.end_date :
                print("YYYYYYYYYYYYYYYYYYY")
            project.save()
            return HttpResponseRedirect('/')
        else :
           return render (request,'projects/NewProject.html',{'form':form,'submitted':submitted})

def editproject(req,project_id):
    project=Project.objects.get(pk=project_id)
    form=ProjectForm(req.POST or None , instance=project)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(f"/details/{project_id}")
    return render(req,'projects/editProject.html',{'form':form,'project':project})



def reportproject(request, pid):
    form = ReportFormProject(request.POST)
    if form.is_valid():
        project = get_object_or_404(Project, id=pid)
        content = form.cleaned_data.get("content")
        ReportProject.objects.create(
            project=project, content=content, user=request.user)
        messages.success(request, "report sent")
        if ReportProject.objects.all().count() >= 6:
            project.delete()
            return HttpResponseRedirect("/")
    else:
        messages.error(request, "report unsent")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    # hadeer


def reportcomment(request, pid):
    form = ReportFormComment(request.POST)
    if form.is_valid():
        comment = get_object_or_404(Comment, id=pid)
        content = form.cleaned_data.get("content")
        ReportComment.objects.create(
            comment=comment, content=content, user=request.user)
        messages.success(request, "report sent")
        if ReportComment.objects.all().count() >= 3:
            comment.delete()
            return HttpResponseRedirect("/")
    else:
        messages.error(request, "report unsent")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    # hadeer


def donate(request, pid):
    form = DonationForm(request.POST)
    if form.is_valid():
        project = get_object_or_404(Project, id=pid)
        amount = form.cleaned_data.get("amount")
        Donation.objects.create(owner=myuser.objects.get(Email=request.session['Email']),
                                project=Project.objects.get(pk=pid), amount=request.POST['amount'])
        donate = project.donationMoney()
        if project.totalTarget == donate['amount__sum']:
            Project.objects.filter(id=pid).delete()
        return HttpResponseRedirect("/")
    # hadeer


def rate(request, pid):
    form = RatingForm(request.POST)
    if form.is_valid():
        project = get_object_or_404(Project, id=pid)
        rate = form.cleaned_data.get("rate")
        print(rate)
        print(Rate.objects.filter(user=myuser.objects.get(Email=request.session['Email'])).filter(
            project=Project.objects.filter(id=pid)[0]).count())
        print(Project.objects.filter(id=pid)[0])
        if Rate.objects.filter(user=myuser.objects.get(Email=request.session['Email'])).filter(project=Project.objects.filter(id=pid)[0]).count() < 1 and Project.objects.filter(id=pid)[0] == project:
            Rate.objects.create(
                project=project, rate=rate, user=myuser.objects.get(Email=request.session['Email']))
        else:
            messages.error(request, "you already rate this project")

projectt/templates/projects/AllProjects.html
{%extends '../mainNav.html'%}
{% load static %}

{%block content%}

<div class="text-center">
    <h2 class="my-4 text-center">ALL PROJECTS  </h2>
    
    {% if authenticated %}
     <a class="btn btn-danger"href="/addproject"> Add Project</a>
      {% else %}
      <p> sign in to add new</p>
    {% endif %}
  
    <ul>
    {% for p in object_list %}
       <li> <a href="#" > {{ p }}</a> 

       </li>  
    {% endfor %}
</ul>
</div>
{% endblock %}

projectt/templates/projects/NewProject.html
{%extends '../mainNav.html'%}
{% load static %}
{%block content%}

<div class="text-center">
    <h2 class="my-4 text-center">ADD NEW PROJECT </h2>
    {% if submitted %}
    <p>NEW PROJECT ADDED Successfully</p>
    {%  else %}
    <form method="post"  enctype="multipart/form-data">
        <div class="container bg-light">
            {%csrf_token%}
            <br><br>
            {{form}}
            <br><br>
            <button type="submit" class="btn btn-primary">Add New Project</button><br>
            <br><br>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

projectt/templates/projects/donations.html
{%extends '../mainNav.html'%}
{% load static %}

{%block content%}


    <div class="container mt-3">
       
        <table class="table table-primary table-hover">
          <thead>
            <tr>
              <th>created_at</th>
              <th>Amount</th>
              <th>Project</th>
            </tr>
          </thead>
          <tbody>
            {% for d in list %}
            <tr>
                <td>{{d.created_at}}  </td> 
            <td>{{d.amount}}</td>
            <td>{{d.project}}  </td> 
        </tr>
            {% endfor %}
            </ul>
          </tbody>
        </table>
      </div>

{% endblock %}

projectt/templates/projects/editProject.html
{%extends '../mainNav.html'%}
{% load static %}
{%block content%}

<div class="text-center">
    <h2 class="my-4 text-center">Edit PROJECT </h2>
  
    <form method="post">
        <div class="container bg-light">
            {%csrf_token%}
            <br><br>
            {{form}}
            <br><br>
            <button type="submit" class="btn btn-primary">Edit Project</button><br>
            <br><br>
        </div>
    </form>
  
</div>
{% endblock %}

projectt/templates/projects/profile.html
{% extends "layout/layout1.html" %}
{% load static %}
{% load tag_library %}
{% block content %}

<!--include nav bar-->

{% include "mainNav.html" %}
<!--first section-->
 <!--slider to show five top rated projects-->

 <div style="height:65px;"></div>
 <div class="container mb-5 mt-1">
    <a class="btn btn-primary"href="/addproject"> Add Project</a>
  <div class="container mt-4">
    <h2 class="h1  font-weight-bold text-primary text-decoration">Latest Projects :</h2>
    <!--start projects latest-->
    <div class="row pl-4  mt-5">

        {% for project in list %}
            <div class="col-md-4 mb-3">
                <div class="card w-100 shadow  mb-5 bg-white rounded " style="min-height:600px;max-height:600px;"  >
                    {% if project.first_Projectphoto  %}
                    <img src="{{project.first_Projectphoto.image.url}}" class="card-img-top w-100" height="200" alt="...">
                    {% else %}
                        <img src="{% static 'projects/image/001.jpg' %}" class="card-img-top w-100" height="200" alt="...">
                    {% endif %}

                   <div class="card-body pt-2 pb-0">
                    <h5 class="card-title h4 text-info">{{project.title}}</h5>
                       <h5 class="card-title text-secondary">Created By: <a href="#" class="text-light"> <sapn class="badge badge-success">{{project.user.username}}</sapn></a></h5>
                    <p class="card-text" style="min-height:100px;max-height:100px;" >
                        {{project.details|truncatechars:200}}
                         <button class="badge badge-light btn" data-toggle="modal" data-target="#model2{{forloop.counter}}">Read more</button>
                        <!-- Modal -->
                        <div class="modal fade" id="model2{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="model2{{forloop.counter}}Title" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="model2{{forloop.counter}}Title">{{project.title}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                {{project.details}}
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>
                    </p>
                  </div>
                 <div class="card-body pb-0">
                    <a href="{% url 'projects:detail' project.id %}" class="card-link">Details</a>
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#dnonate{{forloop.counter}}" data-whatever="@mdo">Donate</button>
                    <!--model-->
                     <div class="modal fade" id="dnonate{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="dnonate{{forloop.counter}}Label" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="dnonate{{forloop.counter}}Label">New Donate To {{project.title}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form action="#" method="post" id="donta">
                                {% csrf_token %}
                              <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Recipient To :</label>
                                <input type="text" class="form-control" disabled id="recipient-name" value="{{project.user.username}}">
                              </div>
                              <div class="form-group">
                                <label  class="col-form-label">Qunaty oF Many</label>
                                <input type="number"  class="form-control"  required name="amount"  placeholder="Enter qunaty of mony">
                              </div>
                                <input type="submit" class="btn btn-primary"  value="Donate"  >
                            </form>
                          </div>
                             <div class="modal-footer">
                            <button type="button"  class="btn btn-secondary" data-dismiss="modal">Close</button>

                          </div>
                        </div>
                      </div>
                    </div>
                     </div>
                    <div class="more-info">
                        <div class="row no-gutters ">
                            <div class="col-md-6 border p-1 ">
                                <i class="fas fa-star mr-3"></i>
                                <span class="badge badge-warning">{{project.rating.rate__avg|default_if_none:0|to_int}}</span>
                            </div>
                            <div class="col-md-6 border p-1 ">
                                <i class="fas fa-users mr-3"></i>
                                <span class="badge badge-success">{{project.donationCount|default_if_none:0|to_int}}</span>
                            </div>
                            <div class="col-md-6 border p-1 ">
                                <i class="fas fa-money-check-alt fa-1x mr-3"></i>
                                <span class="badge badge-success mr-3">{{project.donationMoney.amount__sum|default_if_none:0|to_int}} $</span>
                            </div>
                             <div class="col-md-6 border p-1  ">
                                <i class="fas fa-business-time mr-3"></i>
                                <span class="badge badge-success">{{project.donationMoney.amount__sum|default_if_none:0|to_int|sub:project.totalTarget}} $</span>
                            </div>

                        </div>
                    </div>
                  <div class="card-footer text-muted">
                        {{project.get_date}}
                  </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>


<div class="container mt-4">
  <h2 class="h1  font-weight-bold text-success text-decoration">Feature Projects :</h2>
  <!--start projects latest-->
  <div class="row pl-4  mt-5">

      {% for featurePro in featureProjects %}
          <div class="col-md-4 mb-3">
              <div class="card w-100 shadow mb-5 bg-white rounded " style="min-height:600px;max-height:600px;"  >
                  {% if featurePro.project.first_Projectphoto  %}
                  <img src="{{featurePro.project.first_Projectphoto.image.url}}" class="card-img-top w-100" height="200" alt="...">
                  {% else %}
                      <img src="{% static 'projects/image/001.jpg' %}" class="card-img-top w-100" height="200" alt="...">
                  {% endif %}

                 <div class="card-body pt-2 pb-0">
                  <h5 class="card-title h4 text-info">{{featurePro.project.title}}</h5>
                  <h5 class="card-title text-secondary">Created By: <a href="#user" class="text-light"> <sapn class="badge badge-success">{{featurePro.project.user.username}}</sapn></a></h5>
                  <p class="card-text"  style="min-height:100px;max-height:100px;" >
                      {{featurePro.project.details|truncatechars:200}}
                      <button class="badge badge-light btn" data-toggle="modal" data-target="#model{{forloop.counter}}">Read more</button>
                      <!-- Modal -->
                      <div class="modal fade" id="model{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="model{{forloop.counter}}Title" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="model{{forloop.counter}}Title">{{featurePro.project.title}}</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              {{featurePro.project.details}}
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>
                  </p>
                </div>
               <div class="card-body">
                  <a href="{% url 'projects:detail' featurePro.project.id %}" class="card-link">Details</a>

                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#dnonate2{{forloop.counter}}" data-whatever="@mdo">Donate</button>
                  <!--model-->
                   <div class="modal fade" id="dnonate2{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="dnonate2{{forloop.counter}}Label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="dnonate2{{forloop.counter}}Label">New Donate To {{featurePro.project.title}}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <form action="#" method="post" id="dnonate2">
                              {% csrf_token %}
                            <div class="form-group">
                              <label  class="col-form-label">Recipient To :</label>
                              <input type="text" class="form-control" disabled value="{{featurePro.project.user.username}}">
                            </div>
                            <div class="form-group">
                              <label  class="col-form-label">Qunaty oF Many</label>
                              <input type="number"  class="form-control"  required name="amount"  placeholder="Enter qunaty of mony">
                            </div>
                              <input type="submit" class="btn btn-primary"  value="Donate"  >
                          </form>
                        </div>
                           <div class="modal-footer">
                          <button type="button"  class="btn btn-secondary" data-dismiss="modal">Close</button>

                        </div>
                      </div>
                    </div>
                  </div>
               </div>
                     <div class="more-info">
                      <div class="row no-gutters ">
                          <div class="col-md-6 border p-1 ">
                              <i class="fas fa-star mr-3"></i>
                              <span class="badge badge-warning">{{featurePro.project.rating.rate__avg|default_if_none:0|to_int}}</span>
                          </div>
                          <div class="col-md-6 border p-1 ">
                              <i class="fas fa-users mr-3"></i>
                              <span class="badge badge-success">{{featurePro.project.donationCount|default_if_none:0|to_int}}</span>
                          </div>
                          <div class="col-md-6 border p-1 ">
                              <i class="fas fa-money-check-alt fa-1x mr-3"></i>
                              <span class="badge badge-success">{{featurePro.project.donationMoney.amount__sum|default_if_none:0|to_int}} $</span>
                          </div>
                           <div class="col-md-6 border p-1 ">
                              <i class="fas fa-business-time mr-3"></i>
                              <span class="badge badge-success">{{featurePro.project.donationMoney.amount__sum|default_if_none:0|to_int|sub:featurePro.project.totalTarget}} $</span>
                          </div>

                      </div>
                  </div>

                <div class="card-footer text-muted">
                      {{featurePro.project.get_date}}
                </div>
              </div>
          </div>
      {% endfor %}

  </div>
</div>

{% endblock %}
<!--file javascript-->
{% block js %}
<script src="{% static 'projects/js/jquery.bxslider.js'%}"></script>
<script src="{% static 'projects/js/project.js'%}"></script>
{% endblock %}