projectt/projects/urls.py
from django.urls import path
from .views import *
app_name = "projects"
urlpatterns = [
    path('', index),
    path("index", index, name="index"),
    path("categorie/<int:cid>", view, name="show"),
    path("search", search, name="search"),
    path("details/<int:pid>", details, name="detail"),
    path('mydonations/',my_donations,name='mydonations'),
    
    path('projects/',ProjectsList.as_view(),name="projects"),
    path('addproject/',add_project,name="add-project"),
    path('project/<int:pk>',ProjectDetail.as_view(),name="project"),
    path('addcomment/<project_id>',add_comment,name="addcomment"),
    # path('donate/<project_id>',add_donations,name="add-donation"),
    path('updateproject/<int:project_id>',editproject,name="editproject"),
    path('deleteproject/<int:project_id>',deleteproject,name="deleteproject"),
    path('myprojects/',my_projects,name='myprojects'),
    path("report/<int:pid>", reportproject, name="reportproject"),    # hadeer
    path("comment/<int:pid>", reportcomment, name="reportcomment"),    # hadeer
    path("donate/<int:pid>", donate, name="donate"),    # hadeer
    path("rate/<int:pid>", rate, name="rate"),    # hadeer
    
]

projectt/projectt/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import *
from django.conf.urls.static import static
from django.conf import settings
from crowdFunding.views import login, home, edit, delete,signup, activate, mylogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login',login,name='login'),
    path('home', home, name='home'),
    path('edit',edit, name='user_edit'),
    path('delete', delete, name='user_del'),
    path('', include('projects.urls')),
    path('signup/',signup , name = 'signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
    path('logout',mylogout, name='logout')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectt/crowdFunding/models.py
from django.db import models


# Create your models here.
class myuser(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    Email = models.EmailField(max_length=30, unique=True)
    password=models.CharField(max_length=20)
    confirm_password=models.CharField(max_length=20, null=True)
    phone_number = models.CharField(max_length=11)
    profile_picture = models.ImageField(upload_to='images/', default='images/images.jpeg')
    is_active = models.BooleanField(default=False)
    country = models.CharField(max_length=20, null=True)
    birthdate = models.DateField(null=True)
    fb_account = models.URLField(null=True)

    def __str__(self):
        return self.Email

projectt/crowdFunding/forms.py
from django import forms
from .models import myuser

class RegisterationForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    Email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model=myuser
        exclude = ('country','birthdate', 'fb_account','is_active')



class loginForm(forms.ModelForm):
    Email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model=myuser
        fields= ['Email','password']

class EditForm(forms.ModelForm):
    class Meta:
        model = myuser
        exclude = ('Email','confirm_password','is_active')

projectt/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

projectt/templates/basicNav.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

    <title>My Website</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link h6 text-light" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h6 text-light" href="{% url 'signup' %}">Register</a>
                    </li>
                      <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="Categories" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="Categories">
                {% for cate in categories%}
                    <a class="dropdown-item" href="{% url 'projects:show' cate.id %}">{{cate.name}}</a>
                {% endfor %}
            </div>
          </li>

                </ul>

        <form class="form-inline mt-2 mt-md-0" action="{% url 'projects:search' %}" method="get">
            <select class="form-control mr-sm-2" name="mode">
                <option value="1">Tag</option>
                <option value="2">Title</option>
            </select>
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" required name="search">
          <button class="btn btn-outline-light my-2 my-sm-0 mt-md-2 mt-lg-0" type="submit">Search</button>
        </form>

                </ul>
                &nbsp;
                 <form class="form-inline my-2 my-lg-0">

                    <a class="navbar-brand my-2 my-sm-0 h6 text-light">Crowd Funding Web App</a>
                </form>
            </div>
        </div>
    </nav>
    {%block content%}
    {%endblock%}
</body>

</html>

projectt/templates/edit.html
{% extends 'mainNav.html' %}
{%load static%}
{% block content %}
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
<script type='text/javascript'>
       $(document).on('click', '.confirm-delete', function(){
    return confirm('Are you sure you want to delete this?');
})

</script>
<div class="container-fluid mt-7">
    <div class=" mt-5">
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-8 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center ">

                        <div class="col mb-6 ms-3 ">
                            <div class="card-profile-image">
                                <img src="{{current_user.profile_picture.url}}" height="100" width="100" class="rounded-circle"/>
                            </div>
                        </div>
                        <div class="col d-flex justify-content-center ms-5">
                            <a href="{% url 'user_del' %}" class="confirm-delete btn btn btn-danger text-light "
                               data-toggle="modal" data-target="#deleteModal">Delete Account</a>
                            <!-- Modal -->
                            <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Confirmation Message</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" id="modalBody">
                                            <p class="text-left">Enter your password to confirm</p>
                                            <div class="align-content-start">
                                                <input id="passwordConfirmation" type="password"
                                                       class="form-control form-control-alternative"
                                                       placeholder="Enter password">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button id="submitPassword" type="button" class="btn btn-primary">Proceed
                                            </button>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Abort
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{% url 'user_edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h6 class="heading-small text-muted mb-4">User information</h6>
                        <div class="pl-lg-4">

                            <div class="">
                                <div class="form-group">
                                    <label class="form-control-label" for="input-email">Email</label>
                                    <input type="email" id="input-email" class="form-control form-control-alternative"
                                           placeholder="{{ current_user.Email }}" readonly>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_first_name">First name</label>
                                        <input type="text" name="first_name" id="id_first_name"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.first_name}}" maxlength="20" required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_last_name">Last name</label>
                                        <input type="text" name="last_name" id="id_last_name"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.last_name}}" maxlength="20" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">

                                </div>
                            </div>
                        </div>
                        <hr class="my-4"/>
                        <!-- Address -->
                        <h6 class="heading-small text-muted mb-4">Contact information</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_phone">Phone</label>
                                        <input id="id_phone" name="phone_number"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.phone_number}}" type="text"
                                               maxlength="15" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_fb_account">Facebook Profile</label>
                                        <input id="id_fb_account" name="fb_account"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.fb_account}}" type="url">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_avatar">Profile Picture</label>
                                        <input type="file" accept="image/*" name="profile_picture" id="id_avatar"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.profile_picture}}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_country">Country</label>
                                        <input type="text" name="country" id="id_country"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.country}}" maxlength="20">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_birthdate">Birthdate</label>
                                        <input id="id_birthdate" name="birthdate"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.birthdate|date:'Y-m-d'}}" type="date">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="id_pass">Password</label>
                                        <input type="text" name="password" id="id_pass"
                                               class="form-control form-control-alternative"
                                               value="{{current_user.password}}" maxlength="20">
                                    </div>
                                </div>


                            </div>
                            <div class="d-flex justify-content-center">
                                <div class="w-75 text-center">
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <li class="alert alert-danger">{{ error }}</li>
                                    <br>
                                    {% endfor %}
                                    {% endfor %}
                                </div>
                            </div>
                            <br><br>
                            <div class="row justify-content-center">
                                <button type="submit" class="btn btn-dark">Edit Profile</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

projectt/templates/home.html
{%extends 'mainNav.html'%}
{%load static%}
{%block content%}
<link rel="stylesheet" href="{%static 'css/style.css'%}">
<div class="h1 text-primary mt-5 d-flex justify-content-center">Personal Information </div>
<div class="container mt-5 mb-4 p-3 d-flex justify-content-center ">

    <div class="card p-4" style="width:600px">
        <div class="d-flex flex-row justify-content-center align-items-center">
                <span class="name mt-1 mb-3" id="wel" >Hello!</span> </div>
        <div class=" image d-flex flex-column justify-content-center align-items-center ">
            <button class="btn btn-light gap-2">
                <img src="{{ user.profile_picture.url }}" height="100" width="100" /></button>
                      <span class="name mt-3" id="id_first_name"> {{user.first_name}}&nbsp;{{user.last_name}}</span>

            <div class="d-flex flex-row justify-content-center align-items-center gap-2">

                <span class="name mt-3" id="input-email" >{{user.Email}}</span> </div>
            <div class="d-flex flex-row justify-content-center align-items-center mt-3">

                <span class="name mt-3" id="id_phone">{{user.phone_number}}</span> </div>
            <div class=" d-flex mt-2"> <a href="{% url 'user_edit' %}" class="btn btn-dark">Edit Profile</a>
            &nbsp; &nbsp; <a href="{% url 'logout' %}" class="  justify-content-right btn btn-danger">Logout</a></div>
        </div>
    </div>
</div>
{%endblock%}

projectt/templates/login.html
{% extends "layout/layout1.html" %}
{% load static %}
{%block content%}
{%include 'basicNav.html'%}
<link rel="stylesheet" href="{%static 'css/login.css'%}"/>
  <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">

                <div class="col-lg-12 login-title">
                    LOGIN
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                       <form method="post">
        <div class="container bg-light">
            {%csrf_token%}
            <br><br>
            <div class="form-group">
            {{form.as_p}}
                </div>
            <br><br>
            <div class="col-lg-6 login-btm login-button">
            <button type="submit" class="btn btn-outline-primary d-flex justify-content-center">LOGIN</button>
            </div>
            <span class="text-danger">{{errormsg}}</span>
            <br><br>
        </div>
    </form>
                        <br><br><br><br>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
  </div>

{%endblock%}

projectt/templates/mainNav.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

    <title>My Website</title>
</head>

<body class="bg-white">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{%url 'projects:index'%}">Home Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{%url 'home'%}">My profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/myprojects">Projects</a>
                    </li>
                   <li class="nav-item">
                        <a class="nav-link text-white" href="/mydonations">Donations</a>
                    </li>


                <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="Categories" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu text-white" aria-labelledby="Categories">
                {% for cate in categories%}
                    <a class="dropdown-item" href="{% url 'projects:show' cate.id %}">{{cate.name}}</a>
                {% endfor %}
            </div>
          </li>

                </ul>

        <form class="form-inline mt-2 mt-md-0" action="{% url 'projects:search' %}" method="get">
            <select class="form-control mr-sm-2" name="mode">
                <option value="1">Tag</option>
                <option value="2">Title</option>
            </select>
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" required name="search">
          <button class="btn btn-outline-light my-2 my-sm-0 mt-md-2 mt-lg-0" type="submit">Search</button>
        </form>

            </div>
        </div>
    </nav>
    {%block content%}
    {%endblock%}
</body>

</html>

projectt/templates/register.html
{% load static %}
{%block content%}
{%include 'basicNav.html'%}
<link rel="stylesheet" href="{%static 'css/login.css'%}"/>
  <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">

                <div class="col-lg-12 login-title">
                    Register Now!
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                       <form method="post">
        <div class="container bg-light">
            {%csrf_token%}
            <br><br>
            <div class="form-group">
                <form method="POST" enctype="multipart/form-data">
                     {% csrf_token %}
            {{form.as_p}}
                    </form>
                </div>
            <br><br>
            <div class="col-lg-6 login-btm login-button">
            <button type="submit" class="btn btn-outline-primary d-flex justify-content-center">REGISTER</button>
            </div>
            <span class="text-danger">{{errormsg}}</span>
            <br><br>
        </div>
    </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
  </div>

{%endblock%}